services:
  spring:
    build:
      context: ./backend
    container_name: backend-container
    networks: 
      - docker-network
    ports:
      - "8080:8080"
    environment:
      # EC2 내 MySQL에 로컬 연결
      #SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ppurio
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/ppurio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: star8096

  fastapi:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: fastapi-container
    ports:
      - "8000:8000"
    networks:
      - docker-network
    environment:
      AUTO_CATEGORY_KEY: sk-proj-VXwcPzlcS0gr1vjm62FVT3BlbkFJHgphK3z9HJbEJ0JdTLyw

networks:
  docker-network:
    driver: bridge